package com.altran.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;project_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.altran.liferay.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.altran.liferay.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Project
 * @see com.altran.liferay.model.impl.ProjectImpl
 * @see com.altran.liferay.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
     */

    /**
     * Returns the primary key of this project.
     *
     * @return the primary key of this project
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this project.
     *
     * @param primaryKey the primary key of this project
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this project.
     *
     * @return the uuid of this project
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this project.
     *
     * @param uuid the uuid of this project
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the project ID of this project.
     *
     * @return the project ID of this project
     */
    public long getProjectId();

    /**
     * Sets the project ID of this project.
     *
     * @param projectId the project ID of this project
     */
    public void setProjectId(long projectId);

    /**
     * Returns the group ID of this project.
     *
     * @return the group ID of this project
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this project.
     *
     * @param groupId the group ID of this project
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this project.
     *
     * @return the company ID of this project
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this project.
     *
     * @param companyId the company ID of this project
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this project.
     *
     * @return the user ID of this project
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this project.
     *
     * @param userId the user ID of this project
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this project.
     *
     * @return the user uuid of this project
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this project.
     *
     * @param userUuid the user uuid of this project
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this project.
     *
     * @return the user name of this project
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this project.
     *
     * @param userName the user name of this project
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this project.
     *
     * @return the create date of this project
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this project.
     *
     * @param createDate the create date of this project
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this project.
     *
     * @return the modified date of this project
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this project.
     *
     * @param modifiedDate the modified date of this project
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the title of this project.
     *
     * @return the title of this project
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this project.
     *
     * @param title the title of this project
     */
    public void setTitle(String title);

    /**
     * Returns the description of this project.
     *
     * @return the description of this project
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this project.
     *
     * @param description the description of this project
     */
    public void setDescription(String description);

    /**
     * Returns the director of this project.
     *
     * @return the director of this project
     */
    @AutoEscape
    public String getDirector();

    /**
     * Sets the director of this project.
     *
     * @param director the director of this project
     */
    public void setDirector(String director);

    /**
     * Returns the is public of this project.
     *
     * @return the is public of this project
     */
    public boolean getIsPublic();

    /**
     * Returns <code>true</code> if this project is is public.
     *
     * @return <code>true</code> if this project is is public; <code>false</code> otherwise
     */
    public boolean isIsPublic();

    /**
     * Sets whether this project is is public.
     *
     * @param isPublic the is public of this project
     */
    public void setIsPublic(boolean isPublic);

    /**
     * Returns the people of this project.
     *
     * @return the people of this project
     */
    public int getPeople();

    /**
     * Sets the people of this project.
     *
     * @param people the people of this project
     */
    public void setPeople(int people);

    /**
     * Returns the from date of this project.
     *
     * @return the from date of this project
     */
    public Date getFromDate();

    /**
     * Sets the from date of this project.
     *
     * @param fromDate the from date of this project
     */
    public void setFromDate(Date fromDate);

    /**
     * Returns the to date of this project.
     *
     * @return the to date of this project
     */
    public Date getToDate();

    /**
     * Sets the to date of this project.
     *
     * @param toDate the to date of this project
     */
    public void setToDate(Date toDate);

    /**
     * Returns the comments of this project.
     *
     * @return the comments of this project
     */
    @AutoEscape
    public String getComments();

    /**
     * Sets the comments of this project.
     *
     * @param comments the comments of this project
     */
    public void setComments(String comments);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.altran.liferay.model.Project project);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.altran.liferay.model.Project> toCacheModel();

    @Override
    public com.altran.liferay.model.Project toEscapedModel();

    @Override
    public com.altran.liferay.model.Project toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
